# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Shokuji' do

pod 'BALoadingView', '~> 0.1'

end

target 'ShokujiTests' do

end

target 'ShokujiUITests' do

end

